App: Next.js
PeculiarVentures/GammaCV pull request #102
Opened 2021-04-09 09:22 UTC by donskov

Rewrite library [website](https://gammacv.com/) (https://github.com/PeculiarVentures/GammaCV/tree/master/app) using [next.js](https://nextjs.org/) for better search engine.

2021-04-12 09:08 UTC, donskov commented
NPM audit report:

```
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
in 817 scanned packages
```

Snyk report message:
```
Affected module: glob-parent@5.1.1
Introduced through:   next@10.1.3  ›  chokidar@3.5.1  ›  glob-parent@5.1.1
```

`chokidar` repo issue:
https://github.com/paulmillr/chokidar/issues/1076

2021-04-14 09:04 UTC, donskov commented
@apilguk @WorldThirteen Please review it when you have a time.

2021-04-20 09:51 UTC, WorldThirteen requested changes

2021-04-20 09:51 UTC, WorldThirteen commented on app/tsconfig.json
> +    "strict": false,
Do we have a meaningful reason to disable strict mode?

2021-04-20 09:51 UTC, WorldThirteen commented on app/src/pages/example/params.tsx
> +ParamsWrapper.contextTypes = {
use a static property declaration instead?

2021-04-20 09:51 UTC, WorldThirteen commented on app/src/pages/example/index.tsx
> +ExamplePage.contextTypes = {
static type declaration instead?

2021-04-20 09:51 UTC, WorldThirteen commented on app/src/pages/example/index.tsx
> +  checkRerender = (arr: any) => {
```suggestion
  checkRerender = (arr: Uint8Array) => {
```

2021-04-20 09:51 UTC, WorldThirteen commented on app/src/pages/docs/index.tsx
> +            renderers={{
nitpick: move renders fns out of jsx?

2021-04-20 09:51 UTC, WorldThirteen commented on app/pages/_document.tsx
> +            gtag('config', ${process.env.GOOGLE_ANALYTICS});
I've specify GOOGLE_ANALYTICS=helloworld and got:
![image](https://user-images.githubusercontent.com/14346393/115375535-903e3000-a1d6-11eb-88ef-958088491959.png)

It seems `""` are missing.

2021-04-20 09:51 UTC, WorldThirteen commented on app/pages/_document.tsx
> +              accessToken: ${process.env.ROLLBAR_API_KEY},
I've specified ROLLBAR_API_KEY=awikey and got:
![image](https://user-images.githubusercontent.com/14346393/115375789-cc719080-a1d6-11eb-8c47-ba4719a81175.png)

It seems "" are missing.

2021-04-20 15:00 UTC, WorldThirteen approved these changes
SGTM.

2021-04-20 15:04 UTC, merged