App: Add mobile styles
PeculiarVentures/GammaCV pull request #96
Opened 2021-03-22 10:52 UTC by Kharya1337

2021-03-26 12:28 UTC, MarikTar requested changes
<img width="244" alt="Screenshot 2021-03-26 at 14 23 07" src="https://user-images.githubusercontent.com/47363177/112631391-7f9cd300-8e3f-11eb-97cd-9f90e23f98ea.png">

Fix please

2021-03-26 12:51 UTC, MarikTar commented on app/src/components/header/index.module.sass
> +  &:nth-child(4)
Hide this element by class and not by order

2021-03-26 12:54 UTC, MarikTar commented on app/src/components/header/index.module.sass
> +    &:nth-child(3)
Add class please

2021-03-26 13:01 UTC, MarikTar commented on app/src/components/sidebar/sidebar.module.sass
> +  &.visible
Conflict of action with name

2021-03-26 14:49 UTC, MarikTar commented on app/src/pages/example/index.tsx
> +              stroke={isMobile ? '' : 'grey_2'}
```
 borderRadius={!isMobile && 8}
stroke={!isMobile && 'grey_2'}
```

2021-03-26 14:57 UTC, MarikTar commented on app/src/pages/example/params.module.sass
> +      color: white
Use `rgb(var(--white))`, also and in other places

2021-03-26 14:59 UTC, MarikTar commented on app/src/pages/example/params.tsx
> +              color={isMobile ? 'white' : 'dark'}
Duplicated code, please moved to variable

2021-03-26 15:01 UTC, MarikTar commented on app/src/pages/example/params.tsx
> +                  stroke={isMobile ? '' : 'grey_2'}
`!isMobile && 'grey_2'`

2021-03-26 15:17 UTC, MarikTar commented
In `math_pixelwise` showing error and button `Try again` but need show `Try another examples`.

2021-03-26 15:17 UTC, MarikTar requested changes

2021-03-26 15:17 UTC, MarikTar commented on app/src/pages/example/params.tsx
> +              color={isMobile ? 'white' : 'dark_grey'}
Duplicated code, please moved to variable

2021-03-26 15:39 UTC, MarikTar commented on app/src/components/sidebar/sidebar_group.module.sass
> +      margin-bottom: 57px
![image](https://user-images.githubusercontent.com/47363177/112656049-ab2cb700-8e59-11eb-8a48-3133f2f87eda.png)

This not resolve the disappearance of the bottom padding when scrolling on firefox

2021-03-31 10:43 UTC, donskov requested changes

2021-03-31 10:43 UTC, donskov commented on app/src/pages/docs/index.module.sass
> +        border-bottom: 1px solid #f6f6f6
Use color from the theme.

2021-03-31 10:43 UTC, donskov commented on app/src/pages/docs/index.module.sass
> +      border-top: 1px solid #f6f6f6
Use color from the theme.

2021-03-31 10:43 UTC, donskov commented on app/src/pages/example/index.module.sass
> +      color: #f4f5f9
Use color from the theme.

2021-03-31 10:43 UTC, donskov commented on app/src/pages/example/params.tsx
> +          borderRadius={isMobile ? 0 : 8}
Please check border color on mobile.

2021-03-31 10:43 UTC, donskov commented on app/pages/_app.tsx
> +          visible={showSidebar}
Unclear how to use `visible` and `isDocs` props. Unclear how to add styles based on these props.

2021-03-31 10:43 UTC, donskov commented on app/src/components/header/index.module.sass
> +      object-fit: none
I think this style is unused. Please check.

2021-03-31 10:43 UTC, donskov commented on app/src/components/sidebar/sidebar.module.sass
> +    &.docs_page
Unclear styles using.

2021-03-31 11:11 UTC, Kharya1337 commented on app/src/pages/example/params.tsx
> +          borderRadius={isMobile ? 0 : 8}
On mobile is no border on this Box

2021-04-05 08:49 UTC, merged